/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package work;

import java.awt.Color;
import java.util.Calendar;
import java.util.Enumeration;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author ADMIN
 */
public class FrmHome extends javax.swing.JFrame {

    Color[] c = {Color.RED, Color.BLUE, Color.ORANGE, Color.CYAN, Color.PINK, Color.BLACK, Color.MAGENTA};
    Thread t1 = new Thread(new ThreadColor());
    Thread t2 = new Thread(new ThreadTime());

    class ThreadTime implements Runnable {

        @Override
        public void run() {
            while (true) {
                Calendar c = Calendar.getInstance();
                String hour = (c.getTime().getHours() < 10)
                        ? "0" + c.getTime().getHours() : ""
                        + c.getTime().getHours();
                String minute = (c.getTime().getMinutes() < 10)
                        ? "0" + c.getTime().getMinutes() : ""
                        + c.getTime().getMinutes();
                String secound = (c.getTime().getSeconds() < 10)
                        ? "0" + c.getTime().getSeconds() : ""
                        + c.getTime().getSeconds();
                lbTime.setText(hour + ":" + minute + ":" + secound);
//                try {
//                    Thread.sleep(1000);
//                } catch (InterruptedException ex) {
//                    Logger.getLogger(FrmHome.class.getName()).log(Level.SEVERE, null, ex);
//                }
            }
        }

    }

    public class ThreadColor implements Runnable {

        @Override
        public void run() {
            Color x = lbR.getForeground();
            int index = 0;

            while (true) {
                if (index == c.length - 1) {
                    index = 0;
                } else {
                    index++;
                }
                try {
                    Thread.sleep(800);
                    lbR.setForeground(c[index]);
                } catch (InterruptedException e) {
                    System.out.println("Loi sleep: " + e.getMessage());
                }
            }
        }
    }

    /**
     * Creates new form FrmHome
     */
    public FrmHome() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jbtnVN);
        bg.add(jbtnEN);
        jbtnEN.setSelected(true);
        this.setResizable(false);
        t1.start();
        t2.start();
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbR = new javax.swing.JLabel();
        btnCustomer = new javax.swing.JButton();
        btnBoss = new javax.swing.JButton();
        jbtnVN = new javax.swing.JRadioButton();
        jbtnEN = new javax.swing.JRadioButton();
        lbTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Who you are?");

        lbR.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbR.setText("WELCOME TO APPLESTORE HOLA");

        btnCustomer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnCustomer.setText("CUSTOMER");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnBoss.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBoss.setText("STOREKEEPER");
        btnBoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBossActionPerformed(evt);
            }
        });

        jbtnVN.setText("VIET NAM");
        jbtnVN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVNActionPerformed(evt);
            }
        });

        jbtnEN.setText("ENGLISH");
        jbtnEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnENActionPerformed(evt);
            }
        });

        lbTime.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbR)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCustomer)
                                .addGap(48, 48, 48)
                                .addComponent(btnBoss))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnEN)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtnVN))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTime, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnEN)
                    .addComponent(jbtnVN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbR, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomer)
                    .addComponent(btnBoss))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        String language = null;
        String country = null;
        if (jbtnVN.isSelected()) {
            language = "vn";
            country = "VN";
        }
        if (jbtnEN.isSelected()) {
            language = "en";
            country = "US";
        }
        FrmForCustomer f = new FrmForCustomer(language, country);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnBossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBossActionPerformed
        String lenguage = null;
        String country = null;
        if (jbtnVN.isSelected()) {
            lenguage = "vn";
            country = "VN";
        }
        if (jbtnEN.isSelected()) {
            lenguage = "en";
            country = "US";
        }
        FrProduct f = new FrProduct(lenguage, country);
        f.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBossActionPerformed

    private void jbtnENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnENActionPerformed
        Locale lvn = new Locale("en", "US");
        ResourceBundle rbVn = ResourceBundle.getBundle("MessageBundle", lvn);

        btnBoss.setText(rbVn.getString("Keeper"));
        lbR.setText(rbVn.getString("Welcome"));
        jLabel2.setText(rbVn.getString("Who"));
        btnCustomer.setText(rbVn.getString("Cus"));

    }//GEN-LAST:event_jbtnENActionPerformed

    private void jbtnVNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVNActionPerformed
        Locale lvn = new Locale("vn", "VN");
        ResourceBundle rbVn = ResourceBundle.getBundle("MessageBundle", lvn);
        Enumeration read = rbVn.getKeys();
        while (read.hasMoreElements()) {
            String key = (String) read.nextElement();
            String value = (String) rbVn.getObject(key);
            if (key.equals("Welcome")) {
                lbR.setText(value);
            }
            if (key.equals("Who")) {
                jLabel2.setText(value);
            }
            if (key.equals("Cus")) {
                btnCustomer.setText(value);
            }
            if (key.equals("Keeper")) {
                btnBoss.setText(value);
            }

    }//GEN-LAST:event_jbtnVNActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoss;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jbtnEN;
    private javax.swing.JRadioButton jbtnVN;
    private javax.swing.JLabel lbR;
    private javax.swing.JLabel lbTime;
    // End of variables declaration//GEN-END:variables
}
