package work;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import JDBC.DBContext;
import java.awt.Component;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Enumeration;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import work.PnLogin;

/**
 *
 * @author ACER
 */
public class PnForgot extends javax.swing.JPanel {

    Connection cnn;// ket noi toi db
    Statement stm;  // thuc thi cac cau lenh sql
    ResultSet rs;

    /**
     * Creates new form PnForgot
     */
    public PnForgot(String language, String country) {
        initComponents();
        Locale lvn = new Locale(language, country);
        ResourceBundle rbVn = ResourceBundle.getBundle("MessageBundle", lvn);
        Enumeration read = rbVn.getKeys();
        
        while (read.hasMoreElements()) {
            String key = (String) read.nextElement();
            String value = (String) rbVn.getObject(key);
            
            if (key.equals("Account")) {
                jLabel1.setText(value);
            }
            if (key.equals("Name")) {
                jLabel2.setText(value);
            }
            if (key.equals("Question")) {
                jLabel3.setText(value);
            }
            if (key.equals("Answer")) {
                jLabel4.setText(value);
            }
            if (key.equals("login")) {
                btnLogin.setText(value);
            }
            if (key.equals("TakePass")) {
                btnTakePass.setText(value);
            }
        }
        if (language.equals("vn") && country.equals("VN")) {
            cbo.removeAllItems();
            cbo.addItem("Công việc trong mơ của bạn?");
            cbo.addItem("Sở thích của bạn?");
            cbo.addItem("Đội bóng bạn yêu thích?");
        } else {
            cbo.removeAllItems();
            cbo.addItem("What is your dream job?");
            cbo.addItem("What's your hobby?");
            cbo.addItem("What is your favorite sports team name");
        }
        connect();
    }

    public void connect() {
        try {
            cnn = (new DBContext()).getConnection();
            System.out.println("Connect success");
            
        } catch (Exception e) {
            System.out.println("Connect fail:" + e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        txtAnswer = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnTakePass = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbo = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Account:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Questions:");

        txtAccount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtAnswer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        btnTakePass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTakePass.setText("TAKE PASS");
        btnTakePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTakePassActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Answer:");

        cbo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your dream job?", "What's your hobby?", "What is your favorite sports team name?" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                                    .addComponent(txtName)
                                    .addComponent(txtAnswer)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(cbo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnLogin)
                        .addGap(29, 29, 29)
                        .addComponent(btnTakePass)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTakePass)
                    .addComponent(btnLogin))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String language = "", country = "", s = "";
        if (jLabel1.getText().equalsIgnoreCase("Account:")) {
            language = "en";
            country = "US";
        } else {
            language = "vn";
            country = "VN";
        }
        JFrame parent = null;
        if (common.findParent(this) != null) {
            parent = common.findParent(this);
        }
        if (parent != null) {
            parent.setContentPane(new PnLogin(language, country, s));
            parent.pack();
            parent.setVisible(true);
        }
    }//GEN-LAST:event_btnLoginActionPerformed
    private boolean checkDuplicate(String text) {
        
        try {
            String srtSelect = "select * from tblUser where account='" + text.trim() + "'";
            rs = stm.executeQuery(srtSelect);
            while (rs.next()) {
                return true;
            }
            
        } catch (Exception e) {
            System.out.println("loi:" + e.getMessage());
        }
        return false;
    }
    
    private void btnTakePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTakePassActionPerformed
        String s = "", q = "", r = "";
        if (jLabel1.getText().equalsIgnoreCase("Account:")) {
            s = "Your Password: ";
            q = "Not Valid Account";
            r = "Not Valid Information";
        } else {
            s = "Mật Khẩu của bạn: ";
            q = "Không tồn tại Account";
            r = "Không trùng khớp Thông tin của bạn";
        }
        
        try {
            String srtSelect = "select * from tblUser where account='" + txtAccount.getText().trim() + "'";
            stm = cnn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = stm.executeQuery(srtSelect);
            while (rs.next()) {
                String code = rs.getString(1).trim();
                String name = rs.getString(3);
                String cauHoi = rs.getString(7);
                String traLoi = rs.getString(8);
                String pass = rs.getString(2);
                if (code.equals(txtAccount.getText()) && name.equals(txtName.getText())
                        && traLoi.equals(txtAnswer.getText())
                        && cauHoi.equals((String) cbo.getSelectedItem())) {
                    JOptionPane.showMessageDialog(null, s + pass);
                } else {
                    JOptionPane.showMessageDialog(null, r);
                }
                return;
            }
            JOptionPane.showMessageDialog(null, q);
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, q);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnTakePassActionPerformed

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnTakePass;
    private javax.swing.JComboBox<String> cbo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
